### ISSUE TITLE
Crashes on incoming order: Segmentation fault

### ISSUE THREAD

**Issue by Telcrome** [MASKOR/gologpp#17] opened 2019-11-19 12:53 UTC
To reproduce:

Insert into rcll.gpp:
```
exog_action incoming_order_info(
	number order_id,
	string complexity,
	string base_color
) {
mapping:
	"OrderInterface::/protoboard/order/*" {
		id = order_id,
		complexity = complexity,
		base_color = base_color
	}
}
```
and in gologpp.yaml re-add line 26:
`- "OrderInterface::/protoboard/order/*"`

**Comment by vmatare** [comment] 2019-11-25 13:25
This is triggered by using invalid interface field names, so it is actually not a bug in golog++ itself, but in the [gologpp fawkes plugin](https://github.com/fawkesrobotics/fawkes/tree/common/gologpp/src/plugins/gologpp). It should be fixed (i.e. prevented) now by [69cde23](https://github.com/fawkesrobotics/fawkes/commit/69cde23cc62b64ac2baec417e30442cf60d3d78b).

**Comment by vmatare** [comment] 2019-11-26 16:29
Tested and confirmed fixed.

**Closed by vmatare** 2019-11-26 16:29 UTC
